name: vonova_radiant
description: "An App for vonova_radiant for entry patient data."
publish_to: 'none' 
version: 1.0.3+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  internet_connection_checker_plus: ^2.7.2
  gap: ^3.0.1
  shared_preferences: ^2.5.3
  get: ^5.0.0-release-candidate-9.3.2
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0
  fluttertoast: ^8.2.12
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  clipboard: ^0.1.3
  dio: ^5.8.0+1
  open_file: ^3.5.10
  hive_flutter: ^1.1.0
  fluentui_system_icons: ^1.1.273
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true
  assets:
    - assets/